export const SET_USER = "SET_USER"
export const SET_ACTION_ALERTS = "SET_ACTION_ALERTS"
export const SET_GROUPS = "SET_GROUPS"
export const SET_PLC = "SET_PLC"
export const SET_CHANNELS = "SET_CHANNELS"
